package com.cscec.smartbuild.mapper;

import com.cscec.smartbuild.dto.RoomModel;

import java.util.List;

public interface RoomModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbggenerated Fri Apr 27 14:01:49 CST 2018
     */
    int deleteByPrimaryKey(Long roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbggenerated Fri Apr 27 14:01:49 CST 2018
     */
    int insert(RoomModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbggenerated Fri Apr 27 14:01:49 CST 2018
     */
    int insertSelective(RoomModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbggenerated Fri Apr 27 14:01:49 CST 2018
     */
    RoomModel selectByPrimaryKey(Long roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbggenerated Fri Apr 27 14:01:49 CST 2018
     */
    int updateByPrimaryKeySelective(RoomModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbggenerated Fri Apr 27 14:01:49 CST 2018
     */
    int updateByPrimaryKey(RoomModel record);

    /**
     * 查询所有的房间信息
     * @return
     */
    List<RoomModel> selectAllRooms();

    /**
     * 查询所有的房间信息
     * @return
     */
    List<RoomModel> selectRooms(long buildingNo, String floorNo);
}