package com.cscec.smartbuild.vo;

import com.cscec.smartbuild.dto.RoomModel;

import java.util.List;

/**
 * 房间待选择对象
 *
 * @author wangchun
 * @create 2018-04-27 14:14
 **/
public class RoomsVo {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column building.building_id
     *
     * @mbggenerated Fri Apr 27 14:01:49 CST 2018
     */
    private Long buildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column building.building_no
     *
     * @mbggenerated Fri Apr 27 14:01:49 CST 2018
     */
    private Long buildingNo;

    private List<String> floorNos;

    private List<RoomModel> rooms;

    public Long getBuildingId() {
        return buildingId;
    }

    public void setBuildingId(Long buildingId) {
        this.buildingId = buildingId;
    }

    public Long getBuildingNo() {
        return buildingNo;
    }

    public void setBuildingNo(Long buildingNo) {
        this.buildingNo = buildingNo;
    }

    public List<String> getFloorNos() {
        return floorNos;
    }

    public void setFloorNos(List<String> floorNos) {
        this.floorNos = floorNos;
    }

    public List<RoomModel> getRooms() {
        return rooms;
    }

    public void setRooms(List<RoomModel> rooms) {
        this.rooms = rooms;
    }
}
